language: node_js
sudo: false
jdk:
- oraclejdk8
node_js: lts/*
addon:
  chrome: stable
  firefox: latest
env:
  matrix:
  - CMD=test
  - CMD=lint
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- sleep 5
script:
- npm run $CMD
before_deploy:
- npm run build
