sudo: false
language: node_js
matrix:
  allow_failures:
  - node_js: stable
addon:
  firefox: latest
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
node_js:
- stable
- 6
before_script:
  - npm start
script:
  - sleep 10
  - npm test
notifications:
  email: false
