sudo: false
language: node_js
matrix:
  allow_failures:
  - node_js: stable
addon:
  firefox: latest
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
node_js:
- stable
- 6
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
  - jdk_switcher use oraclejdk8
  - npm start
script:
  - npm test
notifications:
  email: false
