sudo: false
language: node_js
matrix:
  allow_failures:
  - node_js: stable
addon:
  firefox: latest
addons:
  sauce_connect:
    usename: takasho
  jwt:
    secure: <SAUCE_ACCESS_KEY ENCRYPTED>
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
node_js:
- stable
- 6
notifications:
  email: false
