version: "{build}"
environment:
  matrix:
    - nodejs_version: "6"
install:
- choco install firefox
- choco install googlechrome
- ps: Install-Product node $env:nodejs_version
- npm install -g node-gyp
- yarn
test_script:
- npm run test:e2e
build: off
